 FROM guidcruncher/node-pipewire:latest AS base

ARG DATE=""
ARG VERSION=""
ARG BUILD_CONFIG=dev
ARG DEBIAN_FRONTEND=noninteractive
ENV NODE_ENV=development
ARG TARGETARCH
ENV TZ=UTC

RUN groupadd -g 1001 user
RUN useradd user -u 1001 -g 1001 -p t  -m -s /bin/bash
RUN usermod -a -G root user
RUN usermod -a -G audio user
RUN passwd -d user

RUN <<EOF
apk add --no-cache sqlite caddy memcached

mkdir -p \
  /srv \
  /local/state/vopidy/cache \
  /local/config/vopidy \
  /srv/files \
  /srv/files/mixerdesk \
  /srv/files/playlists \
  /srv/files/cache \
  /srv/files/library \
  /srv/files/music \
  /srv/defaults \
  /app/packages/client \
  /app/packages/server \
  /tmp \
  /app/src

npm install -g pm2 node-gyp
EOF

COPY ./container/shared/app/ /app/
COPY ./container/shared/srv/ /srv/
COPY ./container/${BUILD_CONFIG}/app/ /app/
COPY ./container/${BUILD_CONFIG}/srv/ /srv/
RUN chmod +x /app/*.sh

WORKDIR /app/src

COPY . .

RUN chown -R appuser:appuser /app /srv /local

ENV VOPIDY_CONFIG="/local/config/vopidy"
ENV VOPIDY_FILES="/srv/files"
ENV VOPIDY_DB="/local/state/vopidy"
ENV VOPIDY_DEFAULTS="/srv/defaults"
ENV VOPIDY_CACHE="/local/state/vopidy/cache"
ENV SPOTIFY_CLIENT_ID=""
ENV SERVER_PORT=3002
ENV IN_DOCKER=true
ENV BUILD_DATE=$DATE
ENV BUILD_VERSION=$VERSION

WORKDIR /app
USER user

CMD [ "/app/start.sh" ]

