/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalogClock: typeof import('./components/AnalogClock.vue')['default']
    ArtistNames: typeof import('./components/ArtistNames.vue')['default']
    Bookmarks: typeof import('./components/Bookmarks.vue')['default']
    Clock: typeof import('./components/Clock.vue')['default']
    DigitalClock: typeof import('./components/DigitalClock.vue')['default']
    Equaliser: typeof import('./components/Equaliser.vue')['default']
    FileBrowse: typeof import('./components/FileBrowse.vue')['default']
    History: typeof import('./components/History.vue')['default']
    ListItems: typeof import('./components/ListItems.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    NewReleases: typeof import('./components/NewReleases.vue')['default']
    NowPlaying: typeof import('./components/NowPlaying.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    PlaybackQueue: typeof import('./components/PlaybackQueue.vue')['default']
    PlayerControl: typeof import('./components/PlayerControl.vue')['default']
    PopularHistory: typeof import('./components/PopularHistory.vue')['default']
    RadioBrowserBrowse: typeof import('./components/RadioBrowserBrowse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaledImage: typeof import('./components/ScaledImage.vue')['default']
    SearchMusic: typeof import('./components/SearchMusic.vue')['default']
    SpotifyArtist: typeof import('./components/SpotifyArtist.vue')['default']
    SpotifyArtistDetail: typeof import('./components/SpotifyArtistDetail.vue')['default']
    SpotifyBrowse: typeof import('./components/SpotifyBrowse.vue')['default']
    SpotifyItemDetail: typeof import('./components/SpotifyItemDetail.vue')['default']
    StreamBrowse: typeof import('./components/StreamBrowse.vue')['default']
    StreamImport: typeof import('./components/StreamImport.vue')['default']
    TuneinBrowse: typeof import('./components/TuneinBrowse.vue')['default']
    UserProfiles: typeof import('./components/UserProfiles.vue')['default']
    VolumeControl: typeof import('./components/VolumeControl.vue')['default']
    VolumeMixer: typeof import('./components/VolumeMixer.vue')['default']
  }
}
